on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ctramp/barsoom@0.0.8
        with:
          name: 'Tramp'
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"
